project_id = "ibrjwldvyuhwcfzdmimv"

[functions.send-phone-otp]
verify_jwt = false

[functions.verify-phone-otp]
verify_jwt = false

[functions.send-email-otp]
verify_jwt = false

[functions.verify-email-otp]
verify_jwt = false

[functions.full-refresh-titles]
verify_jwt = false

[functions.sync-titles-delta]
verify_jwt = false

[functions.enrich-title-trailers]
verify_jwt = false